package vista.tipopermisos;

import javax.swing.JOptionPane;
import modelos.bd.TipoPermisoBD;
import modelos.md.TipoPermiso;
import vista.VtnPrincipal;
import vista.cargos.VtnCargos;

/**
 *
 * @author Skull
 */
public class FormTipoPermisos extends javax.swing.JInternalFrame {

    private final VtnPrincipal desktop;
    private int pktipoPermiso = 0;
    private TipoPermiso permiso;

    public FormTipoPermisos(int pktipoPermiso, VtnPrincipal desktop) {
        this.desktop = desktop;
        this.pktipoPermiso = pktipoPermiso;
        initComponents();
        cargarTipoPermiso(pktipoPermiso);
    }

    private TipoPermiso getPermiso() {
        TipoPermiso tipoPermiso = new TipoPermiso();
        if (pktipoPermiso == 0) {
            tipoPermiso.setNombre(txtNombrePermiso.getText());
        } else {
            tipoPermiso.setId(pktipoPermiso);
            tipoPermiso.setNombre(txtNombrePermiso.getText());

        }
        return tipoPermiso;
    }

    private void cargarTipoPermiso(int pkTipoPermiso) {
        if (pkTipoPermiso != 0) {
            permiso = TipoPermisoBD.getTipoPermisopor(pkTipoPermiso);
            txtNombrePermiso.setText(permiso.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePermiso = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Registro de Permisos");

        jLabel2.setText("Descripción:");

        txtNombrePermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePermisoActionPerformed(evt);
            }
        });
        txtNombrePermiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePermisoKeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addGap(31, 31, 31)
                        .addComponent(btnGuardar))
                    .addComponent(txtNombrePermiso, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombrePermiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePermisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePermisoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (txtNombrePermiso.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos Vacios", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            if (pktipoPermiso == 0) {
                TipoPermisoBD.insertar(getPermiso());
                JOptionPane.showMessageDialog(this, "Se guardó correctamente!");
                System.out.println("INSERTAR PERMISO");
            } else {
                TipoPermisoBD.update(getPermiso());
                JOptionPane.showMessageDialog(this, "Se modificó correctamente!");
                System.out.println("MODIFICAR PERMISO");
            }
            this.dispose();
            VtnTipoPermisos vtn = new VtnTipoPermisos(desktop);
            this.desktop.desk.add(vtn);
            vtn.show();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        VtnTipoPermisos vtn = new VtnTipoPermisos(desktop);
        this.desktop.desk.add(vtn);
        vtn.show();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombrePermisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePermisoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            String cad = ("" + c).toUpperCase();
            c = cad.charAt(0);
            evt.setKeyChar(c);
        }
    }//GEN-LAST:event_txtNombrePermisoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombrePermiso;
    // End of variables declaration//GEN-END:variables
}
